# service.yml
apiVersion: v1
kind: Service
metadata:
  name: simple-bank-api-service
spec:
  # Deployment의 파드와 연결하기 위한 라벨 선택자입니다.
  selector:
    app: simple-bank-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer