syntax = "proto3";

package pb;

import "google/api/annotations.proto";
import "rpc_create_user.proto";
import "rpc_login_user.proto";
import "rpc_update_user.proto";
import "rpc_verify_email.proto";
import "rpc_create_account.proto";
import "rpc_get_account.proto";
import "rpc_list_account.proto";
import "rpc_renew_access_token.proto";
import "rpc_transfer.proto";

option go_package = "github.com/JeongWoo-Seo/simpleBank/pb";

service SimpleBank {
    rpc CreateUser (CreateUserRequest) returns (CreateUserResponse) {
        option (google.api.http) = {
            post: "/users"
            body: "*"
        };
    }

    rpc LoginUser (LoginUserRequest) returns (LoginUserResponse) {
        option (google.api.http) = {
            post: "/users/login"
            body: "*"
        };
    }

    rpc UpdateUser (UpdateUserRequest) returns (UpdateUserResponse) {
        option (google.api.http) = {
            patch : "/users/update"
            body: "*"
        };
    }

    rpc CreateAccount (CreateAccountRequest) returns (CreateAccountResponse) {
        option (google.api.http) = {
            post: "/accounts"
            body: "*"
        };
    }

    rpc GetAccount (GetAccountRequest) returns (GetAccountResponse) {
        option (google.api.http) = {
            get: "/accounts/{id}"
        };
    }

    rpc ListAccount (ListAccountRequest) returns (ListAccountResponse) {
        option (google.api.http) = {
            get: "/accounts"
        };
    }

    rpc CreateTransfer (CreateTransferRequest) returns (CreateTransferResponse) {
        option (google.api.http) = {
            post: "/transfers"
            body: "*"
        };
    }

    rpc ListTransfer (ListTransferRequest) returns (ListTransferResponse) {
        option (google.api.http) = {
            get: "/transfers"
        };
    }

    rpc RenewAccessToken (RenewAccessTokenRequest) returns (RenewAccessTokenResponse) {
        option (google.api.http) = {
            post: "/tokens/renew_access"
            body: "*"
        };
    }

    rpc VerifyEmail (VerifyEmailRequest) returns (VerifyEmailResponse) {
        option (google.api.http) = {
            get: "/verify_email"
        };
    }
}
