// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: service_simple_bank.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_simple_bank_proto protoreflect.FileDescriptor

const file_service_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x19service_simple_bank.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x15rpc_create_user.proto\x1a\x14rpc_login_user.proto\x1a\x15rpc_update_user.proto\x1a\x16rpc_verify_email.proto\x1a\x18rpc_create_account.proto\x1a\x15rpc_get_account.proto\x1a\x16rpc_list_account.proto\x1a\x1crpc_renew_access_token.proto\x1a\x12rpc_transfer.proto2\x88\a\n" +
	"\n" +
	"SimpleBank\x12N\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/users\x12Q\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/users/login\x12U\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*2\r/users/update\x12Z\n" +
	"\rCreateAccount\x12\x18.pb.CreateAccountRequest\x1a\x19.pb.CreateAccountResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/accounts\x12S\n" +
	"\n" +
	"GetAccount\x12\x15.pb.GetAccountRequest\x1a\x16.pb.GetAccountResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/accounts/{id}\x12Q\n" +
	"\vListAccount\x12\x16.pb.ListAccountRequest\x1a\x17.pb.ListAccountResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/accounts\x12^\n" +
	"\x0eCreateTransfer\x12\x19.pb.CreateTransferRequest\x1a\x1a.pb.CreateTransferResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/transfers\x12U\n" +
	"\fListTransfer\x12\x17.pb.ListTransferRequest\x1a\x18.pb.ListTransferResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/transfers\x12n\n" +
	"\x10RenewAccessToken\x12\x1b.pb.RenewAccessTokenRequest\x1a\x1c.pb.RenewAccessTokenResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/tokens/renew_access\x12U\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/verify_emailB'Z%github.com/JeongWoo-Seo/simpleBank/pbb\x06proto3"

var file_service_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),        // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),         // 1: pb.LoginUserRequest
	(*UpdateUserRequest)(nil),        // 2: pb.UpdateUserRequest
	(*CreateAccountRequest)(nil),     // 3: pb.CreateAccountRequest
	(*GetAccountRequest)(nil),        // 4: pb.GetAccountRequest
	(*ListAccountRequest)(nil),       // 5: pb.ListAccountRequest
	(*CreateTransferRequest)(nil),    // 6: pb.CreateTransferRequest
	(*ListTransferRequest)(nil),      // 7: pb.ListTransferRequest
	(*RenewAccessTokenRequest)(nil),  // 8: pb.RenewAccessTokenRequest
	(*VerifyEmailRequest)(nil),       // 9: pb.VerifyEmailRequest
	(*CreateUserResponse)(nil),       // 10: pb.CreateUserResponse
	(*LoginUserResponse)(nil),        // 11: pb.LoginUserResponse
	(*UpdateUserResponse)(nil),       // 12: pb.UpdateUserResponse
	(*CreateAccountResponse)(nil),    // 13: pb.CreateAccountResponse
	(*GetAccountResponse)(nil),       // 14: pb.GetAccountResponse
	(*ListAccountResponse)(nil),      // 15: pb.ListAccountResponse
	(*CreateTransferResponse)(nil),   // 16: pb.CreateTransferResponse
	(*ListTransferResponse)(nil),     // 17: pb.ListTransferResponse
	(*RenewAccessTokenResponse)(nil), // 18: pb.RenewAccessTokenResponse
	(*VerifyEmailResponse)(nil),      // 19: pb.VerifyEmailResponse
}
var file_service_simple_bank_proto_depIdxs = []int32{
	0,  // 0: pb.SimpleBank.CreateUser:input_type -> pb.CreateUserRequest
	1,  // 1: pb.SimpleBank.LoginUser:input_type -> pb.LoginUserRequest
	2,  // 2: pb.SimpleBank.UpdateUser:input_type -> pb.UpdateUserRequest
	3,  // 3: pb.SimpleBank.CreateAccount:input_type -> pb.CreateAccountRequest
	4,  // 4: pb.SimpleBank.GetAccount:input_type -> pb.GetAccountRequest
	5,  // 5: pb.SimpleBank.ListAccount:input_type -> pb.ListAccountRequest
	6,  // 6: pb.SimpleBank.CreateTransfer:input_type -> pb.CreateTransferRequest
	7,  // 7: pb.SimpleBank.ListTransfer:input_type -> pb.ListTransferRequest
	8,  // 8: pb.SimpleBank.RenewAccessToken:input_type -> pb.RenewAccessTokenRequest
	9,  // 9: pb.SimpleBank.VerifyEmail:input_type -> pb.VerifyEmailRequest
	10, // 10: pb.SimpleBank.CreateUser:output_type -> pb.CreateUserResponse
	11, // 11: pb.SimpleBank.LoginUser:output_type -> pb.LoginUserResponse
	12, // 12: pb.SimpleBank.UpdateUser:output_type -> pb.UpdateUserResponse
	13, // 13: pb.SimpleBank.CreateAccount:output_type -> pb.CreateAccountResponse
	14, // 14: pb.SimpleBank.GetAccount:output_type -> pb.GetAccountResponse
	15, // 15: pb.SimpleBank.ListAccount:output_type -> pb.ListAccountResponse
	16, // 16: pb.SimpleBank.CreateTransfer:output_type -> pb.CreateTransferResponse
	17, // 17: pb.SimpleBank.ListTransfer:output_type -> pb.ListTransferResponse
	18, // 18: pb.SimpleBank.RenewAccessToken:output_type -> pb.RenewAccessTokenResponse
	19, // 19: pb.SimpleBank.VerifyEmail:output_type -> pb.VerifyEmailResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_simple_bank_proto_init() }
func file_service_simple_bank_proto_init() {
	if File_service_simple_bank_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_verify_email_proto_init()
	file_rpc_create_account_proto_init()
	file_rpc_get_account_proto_init()
	file_rpc_list_account_proto_init()
	file_rpc_renew_access_token_proto_init()
	file_rpc_transfer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_simple_bank_proto_rawDesc), len(file_service_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_simple_bank_proto_goTypes,
		DependencyIndexes: file_service_simple_bank_proto_depIdxs,
	}.Build()
	File_service_simple_bank_proto = out.File
	file_service_simple_bank_proto_goTypes = nil
	file_service_simple_bank_proto_depIdxs = nil
}
